In [1]:
import numpy as np
import pandas as pd

In [2]:
# CREATING A DATAFRAME

data = { 'Name': ['john', 'anna' ],
       'age' : [28,34],
       'city' :['new york','paris'],
         'salary': [55000,300000]
       }
df = pd.DataFrame(data)

In [3]:
data_list = [['john', 28, 'New york',55000 ],
       ['anna', 34, 'paris',45000 ]
            ]
df2 = pd.DataFrame(data_list)

In [4]:
df2

      0   1         2      3
0  john  28  New york  55000
1  anna  34     paris  45000

In [5]:
# SELECTION AND iNDEXING OF COLUMNS

In [6]:
df2

      0   1         2      3
0  john  28  New york  55000
1  anna  34     paris  45000

In [7]:
df2[0]

0    john
1    anna
Name: 0, dtype: str

In [8]:
#CREATING A NEW COLUMN
df2["Designation"] = ["doctor","engineer"]

In [9]:
df2

      0   1         2      3 Designation
0  john  28  New york  55000      doctor
1  anna  34     paris  45000    engineer

In [10]:
#REMOVING A COLUMN  axis 0 for horizonal and axis y for vertical
df2.drop('Designation',axis = 1)

      0   1         2      3
0  john  28  New york  55000
1  anna  34     paris  45000

In [11]:
df2

      0   1         2      3 Designation
0  john  28  New york  55000      doctor
1  anna  34     paris  45000    engineer

In [12]:
#SELECTING ROWS
df2

      0   1         2      3 Designation
0  john  28  New york  55000      doctor
1  anna  34     paris  45000    engineer

In [13]:
df2.loc[0]  # loc for rows

0                  john
1                    28
2              New york
3                 55000
Designation      doctor
Name: 0, dtype: object

In [14]:
#SELECTING SUBSETS OF ROWS AND COLUMNS
df.loc[[0,1]][["city","salary"]]  # the o,1 for both rows

       city  salary
0  new york   55000
1     paris  300000

In [15]:
df.loc[[1]][["age"]]

   age
1   34

In [16]:
#CONDITIONAL SELECTION
df2

      0   1         2      3 Designation
0  john  28  New york  55000      doctor
1  anna  34     paris  45000    engineer

In [17]:
df2[df2[1]>30]  #using 1 for the indexing of age

      0   1      2      3 Designation
1  anna  34  paris  45000    engineer

In [21]:
# i only want whose age is abpve 30 and city paris
df2[(df2[1]>27) & (df2[2]=='New york')]

      0   1         2      3 Designation
0  john  28  New york  55000      doctor