In [10]:
#LOADING THE DATA
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv(r'anime.csv')

In [22]:
df.head()

,Title,Score,Vote,Ranked,Popularity,Episodes,Status,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating
0,Sousou no FrierenFrieren: Beyond Journey's End,9.14,128768,1,508,28,Currently Airing,"Sep 29, 2023 to Mar 2024",Fall 2023,"['Aniplex', 'Dentsu', 'Shogakukan-Shueisha Pro...","None found, add some",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older
1,Fullmetal Alchemist: Brotherhood,9.09,2080863,2,3,64,Finished Airing,"Apr 5, 2009 to Jul 4, 2010",Spring 2009,"['Aniplex', 'Square Enix', 'Mainichi Broadcast...","Funimation, Aniplex of America",Bones,Manga,24 min. per ep.,R - 17+ (violence & profanity)
2,Steins;Gate,9.07,1375512,3,13,24,Finished Airing,"Apr 6, 2011 to Sep 14, 2011",Spring 2011,"['Frontier Works', 'Media Factory', 'Kadokawa ...",Funimation,White Fox,Visual novel,24 min. per ep.,PG-13 - Teens 13 or older
3,Gintama°Gintama Season 4,9.06,246431,4,337,51,Finished Airing,"Apr 8, 2015 to Mar 30, 2016",Spring 2015,"['TV Tokyo', 'Aniplex', 'Dentsu']","Funimation, Crunchyroll",Bandai Namco Pictures,Manga,24 min. per ep.,PG-13 - Teens 13 or older
4,Shingeki no Kyojin Season 3 Part 2Attack on Ti...,9.05,1545108,5,21,10,Finished Airing,"Apr 29, 2019 to Jul 1, 2019",Spring 2019,"['Production I.G', 'Dentsu', 'Mainichi Broadca...",Funimation,Wit Studio,Manga,23 min. per ep.,R - 17+ (violence & profanity)

In [23]:
#MAKE A NEW COLUMN FOR EPISODE COUNT

In [24]:
df["Episodes"] = df["Episodes"].astype(str).str.extract(r'(\d+)')

In [15]:
def extract_episodes(txt):
    check = True
    data = ""
    for i in txt:
        if i == 'Episodes':
            check = True
        if check == True:
            data += i
            break
    return data

In [16]:
df["Episodes"].apply(extract_episodes)

0       2
1       6
2       2
3       5
4       1
       ..
9995    1
9996    1
9997    2
9998    2
9999    1
Name: Episodes, Length: 10000, dtype: str

In [8]:
#MAKE A NEW COLUMN FOR TIME STAMP

In [9]:
df.loc[0]['Title']

"Sousou no FrierenFrieren: Beyond Journey's End"

In [17]:
df["Timestamp"] = df["Aired"]

In [18]:
df[["Title", "Aired", "Timestamp"]].head()

,Title,Aired,Timestamp
0,Sousou no FrierenFrieren: Beyond Journey's End,"Sep 29, 2023 to Mar 2024","Sep 29, 2023 to Mar 2024"
1,Fullmetal Alchemist: Brotherhood,"Apr 5, 2009 to Jul 4, 2010","Apr 5, 2009 to Jul 4, 2010"
2,Steins;Gate,"Apr 6, 2011 to Sep 14, 2011","Apr 6, 2011 to Sep 14, 2011"
3,Gintama°Gintama Season 4,"Apr 8, 2015 to Mar 30, 2016","Apr 8, 2015 to Mar 30, 2016"
4,Shingeki no Kyojin Season 3 Part 2Attack on Ti...,"Apr 29, 2019 to Jul 1, 2019","Apr 29, 2019 to Jul 1, 2019"

In [19]:
df["Year"]= df["Aired"].str.extract(r"(\d{4})")

In [20]:
df[["Title", "Aired", "Year"]].head()

,Title,Aired,Year
0,Sousou no FrierenFrieren: Beyond Journey's End,"Sep 29, 2023 to Mar 2024",2023
1,Fullmetal Alchemist: Brotherhood,"Apr 5, 2009 to Jul 4, 2010",2009
2,Steins;Gate,"Apr 6, 2011 to Sep 14, 2011",2011
3,Gintama°Gintama Season 4,"Apr 8, 2015 to Mar 30, 2016",2015
4,Shingeki no Kyojin Season 3 Part 2Attack on Ti...,"Apr 29, 2019 to Jul 1, 2019",2019

In [29]:
def extract_duration(aired):
    dates = aired.split("to")

    if len(dates)!=2:
        return None

        start = pd.to_datetime(dates[0],errors="coerce")
        if pd.isna(start) or pd.isna(end):
            return None

        return(end.year-start.year) * 12 + end.month - start.month
df["Duration_Months"] = df["Aired"].apply(extract_duration)
df_new = df[["Title","Episodes","Duration_Months"]]

In [31]:
df_new.head()

                                               Title Episodes Duration_Months
0     Sousou no FrierenFrieren: Beyond Journey's End       28            None
1                   Fullmetal Alchemist: Brotherhood       64            None
2                                        Steins;Gate       24            None
3                           Gintama°Gintama Season 4       51            None
4  Shingeki no Kyojin Season 3 Part 2Attack on Ti...       10            None

In [32]:
df_new = df[["Title","Episodes","Ranked"]]

In [33]:
df_new.head()

                                               Title Episodes  Ranked
0     Sousou no FrierenFrieren: Beyond Journey's End       28       1
1                   Fullmetal Alchemist: Brotherhood       64       2
2                                        Steins;Gate       24       3
3                           Gintama°Gintama Season 4       51       4
4  Shingeki no Kyojin Season 3 Part 2Attack on Ti...       10       5

In [37]:
df_new

                                                  Title Episodes  Ranked
0        Sousou no FrierenFrieren: Beyond Journey's End       28       1
1                      Fullmetal Alchemist: Brotherhood       64       2
2                                           Steins;Gate       24       3
3                              Gintama°Gintama Season 4       51       4
4     Shingeki no Kyojin Season 3 Part 2Attack on Ti...       10       5
...                                                 ...      ...     ...
9995       Sword Art Online: Alicization - Recollection        1    5000
9996  Taimadou Gakuen 35 Shiken ShoutaiAnti-Magic Ac...       12    5001
9997         Taiyou no Mokushiroku: A Spirit of the Sun        2    5002
9998                   Weiß Kreuz OVAKnight Hunters OVA        2    5003
9999          Wo Shi Da Shenxian 2nd SeasonDa Shen Xian       16    5004

[10000 rows x 3 columns]

In [38]:
df["Score"].unique

<bound method Series.unique of 0       9.14
1       9.09
2       9.07
3       9.06
4       9.05
        ...
9995    6.81
9996    6.81
9997    6.81
9998    6.81
9999    6.81
Name: Score, Length: 10000, dtype: float64>

In [39]:
df["Title"]

0          Sousou no FrierenFrieren: Beyond Journey's End
1                        Fullmetal Alchemist: Brotherhood
2                                             Steins;Gate
3                                Gintama°Gintama Season 4
4       Shingeki no Kyojin Season 3 Part 2Attack on Ti...
                              ...
9995         Sword Art Online: Alicization - Recollection
9996    Taimadou Gakuen 35 Shiken ShoutaiAnti-Magic Ac...
9997           Taiyou no Mokushiroku: A Spirit of the Sun
9998                     Weiß Kreuz OVAKnight Hunters OVA
9999            Wo Shi Da Shenxian 2nd SeasonDa Shen Xian
Name: Title, Length: 10000, dtype: str

In [40]:
df[df["Episodes"] == df["Episodes"].max()]

,Title,Score,Vote,Ranked,Popularity,Episodes,Status,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Duration_Months
130,Uchuu KyoudaiSpace Brothers,8.49,52121,131,1211,99,Finished Airing,"Apr 1, 2012 to Mar 22, 2014",Spring 2012,"['Yomiuri Telecasting', 'Trinity Sound']",Sentai Filmworks,A-1 Pictures,Manga,24 min. per ep.,PG-13 - Teens 13 or older,None
3124,Mister Ajikko,7.20,1171,3129,8316,99,Finished Airing,"Oct 8, 1987 to Sep 28, 1989",Fall 1987,['TV Tokyo'],"None found, add some",Sunrise,Manga,24 min. per ep.,G - All Ages,None
5130,Uchuu KyoudaiSpace Brothers,8.49,52121,131,1211,99,Finished Airing,"Apr 1, 2012 to Mar 22, 2014",Spring 2012,"['Yomiuri Telecasting', 'Trinity Sound']",Sentai Filmworks,A-1 Pictures,Manga,24 min. per ep.,PG-13 - Teens 13 or older,None
8124,Mister Ajikko,7.20,1171,3128,8316,99,Finished Airing,"Oct 8, 1987 to Sep 28, 1989",Fall 1987,['TV Tokyo'],"None found, add some",Sunrise,Manga,24 min. per ep.,G - All Ages,None