In [22]:
# FINDING MISSING DATA
import numpy as np
import pandas as pd

In [32]:
data = {
    'A' : [1,2,np.nan, 4,5],   # this nan is the null or missing data
    'B' : [1, 2,3,4,5],
    'C' : [1,2,3, np.nan , np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [33]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [34]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [35]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [36]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [37]:
# REMOVING MISSSING DATA
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [38]:
df.dropna() #it removed all the null value

     A  B    C    D
0  1.0  1  1.0  1.0

In [39]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [47]:
df.dropna(thresh=4)  # threshold keeps only whose have that number of non null values

     A  B    C    D
0  1.0  1  1.0  1.0

In [48]:
#FILLING THE MISSING DATA
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [49]:
df.fillna(0)  # fillna fills the value at the position of null  
#but it will not remove or add permanently untill we use , inplace = true

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [50]:
values = {'A':0 , 'B' : 100,'c':300,'D':400}
df.fillna(value = values)  # it will fill the values column wise

     A  B    C      D
0  1.0  1  1.0    1.0
1  2.0  2  2.0  400.0
2  0.0  3  3.0  400.0
3  4.0  4  NaN  400.0
4  5.0  5  NaN    5.0

In [51]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [52]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0